name: Nightly Debt Audit
on:
  schedule:
    - cron: '0 2 * * *'  # Run at 2 AM UTC daily
  workflow_dispatch:  # Allow manual trigger

jobs:
  debt-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with: { node-version: '20', cache: 'npm' }
      
      - run: npm ci
      
      # Take debt snapshot
      - run: npm run debt:snapshot
      
      # Compare with previous snapshot
      - run: npm run debt:compare || echo "No previous snapshot to compare"
      
      # Check if debt increased
      - name: Check debt trend
        id: debt-check
        run: |
          if [ -f "reports/debt/debt-$(date +%Y-%m-%d).json" ]; then
            echo "Debt snapshot created successfully"
            echo "debt_increased=false" >> $GITHUB_OUTPUT
          else
            echo "Failed to create debt snapshot"
            echo "debt_increased=true" >> $GITHUB_OUTPUT
          fi
      
      # Comment on debt issue if debt increased
      - name: Comment on debt issue
        if: steps.debt-check.outputs.debt_increased == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const { data: issues } = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: 'tech-debt,frontend',
              state: 'open'
            });
            
            if (issues.length > 0) {
              const debtIssue = issues[0];
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: debtIssue.number,
                body: `🚨 **Debt Alert** - ${new Date().toISOString().split('T')[0]}
                
                Debt snapshot failed or debt increased. Please check the latest snapshot and update the burn-down plan.
                
                [View latest snapshot](https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId})`
              });
            }
      
      # Upload debt artifacts
      - uses: actions/upload-artifact@v4
        with:
          name: debt-snapshot-${{ github.run_number }}
          path: reports/debt/
