import {
  DashboardCardDefinition,
  DashboardCardKey,
} from './dashboard-card-types';

export const DASHBOARD_CARD_DEFINITIONS: DashboardCardDefinition[] = [
  {
    cardKey: 'my_tasks_today',
    title: 'My Tasks Today',
    description: 'Personal tasks due today.',
    category: 'featured',
    supportedScopes: ['home'],
    defaultDisplayType: 'metric',
    defaultSize: 'small',
    drilldownRouteTemplate: '/my-tasks?view=assigned&filter=today',
    resolverKey: 'my_tasks_today',
  },
  {
    cardKey: 'overdue_tasks',
    title: 'Overdue Tasks',
    description: 'Tasks that are past due and still open.',
    category: 'tasks',
    supportedScopes: ['home', 'workspace'],
    defaultDisplayType: 'metric',
    defaultSize: 'small',
    drilldownRouteTemplate: '/my-tasks?view=assigned&filter=overdue',
    resolverKey: 'overdue_tasks',
  },
  {
    cardKey: 'blocked_tasks',
    title: 'Blocked Tasks',
    description: 'Tasks currently blocked.',
    category: 'tasks',
    supportedScopes: ['home', 'workspace'],
    defaultDisplayType: 'metric',
    defaultSize: 'small',
    drilldownRouteTemplate: '/my-tasks?view=assigned&filter=blocked',
    resolverKey: 'blocked_tasks',
  },
  {
    cardKey: 'tasks_by_status',
    title: 'Tasks by Status',
    description: 'Status split for current task scope.',
    category: 'tasks',
    supportedScopes: ['home', 'workspace'],
    defaultDisplayType: 'chart',
    defaultSize: 'medium',
    drilldownRouteTemplate: '/my-tasks',
    resolverKey: 'tasks_by_status',
  },
  {
    cardKey: 'projects_at_risk',
    title: 'Projects At Risk',
    description: 'Projects marked at-risk or blocked.',
    category: 'project-health',
    supportedScopes: ['workspace'],
    defaultDisplayType: 'metric',
    defaultSize: 'small',
    drilldownRouteTemplate: '/projects?filter=at-risk',
    resolverKey: 'projects_at_risk',
  },
  {
    cardKey: 'upcoming_deadlines',
    title: 'Upcoming Deadlines',
    description: 'Deadlines due in the next 7 days.',
    category: 'tasks',
    supportedScopes: ['home', 'workspace'],
    defaultDisplayType: 'metric',
    defaultSize: 'small',
    drilldownRouteTemplate: '/my-tasks?filter=upcoming',
    resolverKey: 'upcoming_deadlines',
  },
  {
    cardKey: 'milestone_progress',
    title: 'Milestone Progress',
    description: 'Completed milestones vs total milestones.',
    category: 'project-health',
    supportedScopes: ['workspace'],
    defaultDisplayType: 'chart',
    defaultSize: 'medium',
    drilldownRouteTemplate: '/projects?view=milestones',
    resolverKey: 'milestone_progress',
  },
  {
    cardKey: 'workload_distribution',
    title: 'Workload Distribution',
    description: 'Allocation distribution across visible assignments.',
    category: 'resources',
    supportedScopes: ['workspace'],
    defaultDisplayType: 'chart',
    defaultSize: 'medium',
    drilldownRouteTemplate: '/resources',
    resolverKey: 'workload_distribution',
  },
  {
    cardKey: 'resource_capacity',
    title: 'Resource Capacity',
    description: 'Over-capacity and average allocation metrics.',
    category: 'resources',
    supportedScopes: ['workspace'],
    defaultDisplayType: 'metric',
    defaultSize: 'small',
    drilldownRouteTemplate: '/capacity',
    resolverKey: 'resource_capacity',
  },
  {
    cardKey: 'active_risks',
    title: 'Active Risks',
    description: 'Open risks across visible projects.',
    category: 'governance',
    supportedScopes: ['workspace'],
    defaultDisplayType: 'metric',
    defaultSize: 'small',
    drilldownRouteTemplate: '/risks',
    resolverKey: 'active_risks',
  },
];

export const DEFAULT_HOME_CARD_KEYS: DashboardCardKey[] = [
  'my_tasks_today',
  'overdue_tasks',
  'blocked_tasks',
  'upcoming_deadlines',
  'tasks_by_status',
];

export const DEFAULT_WORKSPACE_CARD_KEYS: DashboardCardKey[] = [
  'projects_at_risk',
  'overdue_tasks',
  'blocked_tasks',
  'workload_distribution',
  'milestone_progress',
  'resource_capacity',
  'active_risks',
  'upcoming_deadlines',
];

