version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: zephix-postgres-dev
    environment:
      POSTGRES_DB: zephix_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - zephix-dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: zephix-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - zephix-dev
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend Service
  backend:
    build:
      context: ./zephix-backend
      dockerfile: Dockerfile.dev
    container_name: zephix-backend-dev
    environment:
      NODE_ENV: development
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_DATABASE: zephix_dev
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      JWT_EXPIRES_IN: 24h
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - ./zephix-backend:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - zephix-dev
    command: npm run start:dev

  # Frontend Service
  frontend:
    build:
      context: ./zephix-frontend
      dockerfile: Dockerfile.dev
    container_name: zephix-frontend-dev
    environment:
      VITE_API_BASE_URL: http://localhost:3000
      VITE_APP_NAME: Zephix
      VITE_APP_VERSION: 1.0.0
    ports:
      - "5173:5173"
    volumes:
      - ./zephix-frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - zephix-dev
    command: npm run dev:local

  # VS Code Server
  code-server:
    image: codercom/code-server:latest
    container_name: zephix-code-server
    environment:
      PASSWORD: zephix123
      DOCKER_USER: root
    ports:
      - "8080:8080"
    volumes:
      - ./:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
      - code_server_data:/home/coder
    networks:
      - zephix-dev
    command: --bind-addr 0.0.0.0:8080 --auth password

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: zephix-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
      - code-server
    networks:
      - zephix-dev

volumes:
  postgres_data:
  redis_data:
  code_server_data:

networks:
  zephix-dev:
    driver: bridge