[build]
  publish = "."
  command = "echo 'No build step required for static site'"

[build.environment]
  NODE_VERSION = "20"

# Redirect www to apex domain
[[redirects]]
  from = "https://www.getzephix.com/*"
  to = "https://getzephix.com/:splat"
  status = 301
  force = true

# Redirect HTTP to HTTPS
[[redirects]]
  from = "http://getzephix.com/*"
  to = "https://getzephix.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.getzephix.com/*"
  to = "https://getzephix.com/:splat"
  status = 301
  force = true

# SPA fallback for clean URLs (optional)
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' https://f.convertkit.com https://app.convertkit.com https://fonts.googleapis.com https://plausible.io https://www.googletagmanager.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      font-src 'self' https://fonts.gstatic.com;
      img-src 'self' data: https:;
      connect-src 'self' https://app.convertkit.com https://plausible.io https://www.google-analytics.com https://analytics.google.com;
      form-action 'self' https://app.convertkit.com;
      frame-ancestors 'none';
      base-uri 'self';
    """

# Cache static assets
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.ico"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# HTML files - shorter cache
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"
