version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "malikadeel"
    assignees:
      - "malikadeel"
    commit-message:
      prefix: "chore"
      include: "scope"
    # Group updates for better PR management
    groups:
      dev-dependencies:
        patterns:
          - "@types/*"
          - "@testing-library/*"
          - "eslint*"
          - "typescript*"
          - "vitest*"
          - "vite*"
        update-types:
          - "minor"
          - "patch"
      security-updates:
        patterns:
          - "*"
        update-types:
          - "security"
    # Ignore major version updates for production stability
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
