# Global Nixpacks Configuration
# Forces nixpacks usage for entire monorepo

[phases.setup]
nixPkgs = ["nodejs_20", "yarn"]

[phases.install]
cmds = ["echo 'Using nixpacks builder'"]

[phases.build]
cmds = ["echo 'Build phase completed'"]

[start]
cmd = "echo 'Service started'"

[variables]
# Force nixpacks usage - GLOBAL ENFORCEMENT
BUILDER = "nixpacks"
RAILWAY_BUILDER = "nixpacks"
USE_NIXPACKS = "true"
DISABLE_DOCKER = "true"
FORCE_NIXPACKS = "true"
RAILWAY_FORCE_NIXPACKS = "true"
BUILDER_OVERRIDE = "nixpacks"
NIXPACKS_FORCE = "true"
DOCKER_DISABLED = "true"
NO_DOCKER_BUILD = "true"
SKIP_DOCKER = "true"

# Explicitly disable Docker
DOCKER_BUILD = "false"
USE_DOCKER = "false"
RAILWAY_DOCKER = "false"
