/**
 * SEC-UPGRADE-1 unit 2 (argon2 bump) — verify-compatibility regression guard.
 *
 * The AM-1 login rescue reads pre-existing $argon2id$ hashes minted months ago
 * (by argon2 0.31.x) and re-hashes them to bcrypt. If a future argon2 major bump
 * ever changed verify()'s handling of old hash parameters/format, the rescue
 * would SILENTLY stop rescuing — same invisible-lockout class as AM-1, reborn,
 * with victims structurally unable to report it.
 *
 * This test uses the REAL argon2 module (NOT mocked — the rescue spec mocks it;
 * per the mocked-QueryBuilder lesson, pair the mocked test with a real one) to
 * assert the installed version still validates a hash minted by 0.31.2. The
 * fixture hash below is frozen: it was generated by argon2 0.31.2 as
 * argon2.hash('KnownProof123!'). If this test ever fails after a bump, the
 * rescue is broken — do NOT delete or regenerate the fixture; investigate.
 */
import * as argon2 from 'argon2';

// Frozen: argon2 0.31.2 output for the plaintext below. Not a live secret —
// a throwaway test password's hash, kept verbatim to pin cross-version verify.
const HASH_FROM_0_31 =
  '$argon2id$v=19$m=65536,t=3,p=4$uc69lxsdHmSU3VWcuB4e6w$9xJoVpGOVEIPV3A5TO97faOED9SAasub7pPXR1HlKLI';
const PLAINTEXT = 'KnownProof123!';

describe('argon2 verify — cross-version compatibility (AM-1 rescue survives the bump)', () => {
  it('the installed argon2 validates a hash minted by 0.31.2 with the correct password', async () => {
    await expect(argon2.verify(HASH_FROM_0_31, PLAINTEXT)).resolves.toBe(true);
  });

  it('rejects a wrong password against the same old hash', async () => {
    await expect(argon2.verify(HASH_FROM_0_31, 'not-the-password')).resolves.toBe(
      false,
    );
  });

  it('parses the standard PHC argon2id format (params embedded in the hash)', () => {
    expect(HASH_FROM_0_31).toMatch(/^\$argon2id\$v=19\$m=\d+,t=\d+,p=\d+\$/);
  });
});
