import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateResourceTables1756271690591 implements MigrationInterface {
    name = 'CreateResourceTables1756271690591'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "public"."IDX_users_reset_token"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_users_verification_token"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_users_email_verified"`);
        await queryRunner.query(`CREATE TABLE "refresh_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "token" character varying NOT NULL, "expiresAt" TIMESTAMP NOT NULL, "isRevoked" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid, CONSTRAINT "UQ_4542dd2f38a61354a040ba9fd57" UNIQUE ("token"), CONSTRAINT "PK_7d8bee0204106019488c4c50ffa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."user_organizations_role_enum" AS ENUM('owner', 'admin', 'pm', 'viewer')`);
        await queryRunner.query(`CREATE TABLE "user_organizations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "organizationId" uuid NOT NULL, "role" "public"."user_organizations_role_enum" NOT NULL DEFAULT 'viewer', "isActive" boolean NOT NULL DEFAULT true, "permissions" jsonb NOT NULL DEFAULT '{}', "joinedAt" date, "lastAccessAt" date, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_51ed3f60fdf013ee5041d2d4d3d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_USER_ORG_ROLE" ON "user_organizations" ("role") `);
        await queryRunner.query(`CREATE INDEX "IDX_USER_ORG_ACTIVE" ON "user_organizations" ("isActive") `);
        await queryRunner.query(`CREATE INDEX "IDX_USER_ORG_ORG_ID" ON "user_organizations" ("organizationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_USER_ORG_USER_ID" ON "user_organizations" ("userId") `);
        await queryRunner.query(`CREATE TABLE "workflow_versions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workflowTemplateId" uuid NOT NULL, "createdBy" uuid NOT NULL, "versionNumber" integer NOT NULL, "versionName" character varying(255), "description" text, "templateData" jsonb NOT NULL, "changeLog" jsonb NOT NULL DEFAULT '{}', "isPublished" boolean NOT NULL DEFAULT false, "publishedAt" TIMESTAMP, "publishedBy" uuid, "metadata" jsonb NOT NULL DEFAULT '{}', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "PK_a84eb8dc6065f33ce4b1447955f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_WORKFLOW_VERSION_CREATED_BY" ON "workflow_versions" ("createdBy") `);
        await queryRunner.query(`CREATE INDEX "IDX_WORKFLOW_VERSION_NUMBER" ON "workflow_versions" ("workflowTemplateId", "versionNumber") `);
        await queryRunner.query(`CREATE INDEX "IDX_WORKFLOW_VERSION_TEMPLATE" ON "workflow_versions" ("workflowTemplateId") `);
        await queryRunner.query(`CREATE TYPE "public"."workflow_templates_type_enum" AS ENUM('waterfall', 'agile', 'hybrid', 'custom')`);
        await queryRunner.query(`CREATE TYPE "public"."workflow_templates_status_enum" AS ENUM('active', 'draft', 'archived', 'deprecated')`);
        await queryRunner.query(`CREATE TABLE "workflow_templates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organizationId" uuid NOT NULL, "createdBy" uuid NOT NULL, "name" character varying(255) NOT NULL, "description" text, "type" "public"."workflow_templates_type_enum" NOT NULL DEFAULT 'custom', "status" "public"."workflow_templates_status_enum" NOT NULL DEFAULT 'draft', "metadata" jsonb NOT NULL DEFAULT '{}', "isDefault" boolean NOT NULL DEFAULT false, "isPublic" boolean NOT NULL DEFAULT false, "version" integer NOT NULL DEFAULT '1', "tags" jsonb, "usageCount" integer NOT NULL DEFAULT '0', "lastUsedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "PK_de336a1fce23ad3261d49423eae" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_WORKFLOW_TEMPLATE_CREATED_BY" ON "workflow_templates" ("createdBy") `);
        await queryRunner.query(`CREATE INDEX "IDX_WORKFLOW_TEMPLATE_STATUS" ON "workflow_templates" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_WORKFLOW_TEMPLATE_TYPE" ON "workflow_templates" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_WORKFLOW_TEMPLATE_ORG" ON "workflow_templates" ("organizationId") `);
        await queryRunner.query(`CREATE TYPE "public"."workflow_approvals_type_enum" AS ENUM('stage_entry', 'stage_exit', 'milestone', 'deliverable', 'budget', 'timeline', 'quality', 'custom')`);
        await queryRunner.query(`CREATE TYPE "public"."workflow_approvals_status_enum" AS ENUM('pending', 'approved', 'rejected', 'escalated', 'cancelled')`);
        await queryRunner.query(`CREATE TYPE "public"."workflow_approvals_level_enum" AS ENUM('team_lead', 'project_manager', 'department_head', 'executive', 'stakeholder', 'custom')`);
        await queryRunner.query(`CREATE TABLE "workflow_approvals" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workflowStageId" uuid NOT NULL, "reviewerId" uuid NOT NULL, "type" "public"."workflow_approvals_type_enum" NOT NULL DEFAULT 'custom', "status" "public"."workflow_approvals_status_enum" NOT NULL DEFAULT 'pending', "level" "public"."workflow_approvals_level_enum" NOT NULL DEFAULT 'team_lead', "title" character varying(255) NOT NULL, "description" text, "criteria" jsonb NOT NULL DEFAULT '{}', "requiredDocuments" jsonb NOT NULL DEFAULT '{}', "dueDate" TIMESTAMP, "approvedAt" TIMESTAMP, "rejectedAt" TIMESTAMP, "comments" text, "rejectionReason" text, "escalationRules" jsonb NOT NULL DEFAULT '{}', "isRequired" boolean NOT NULL DEFAULT false, "canBeSkipped" boolean NOT NULL DEFAULT false, "metadata" jsonb NOT NULL DEFAULT '{}', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "PK_36949dc46e63a84b77b624651ef" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_WORKFLOW_APPROVAL_TYPE" ON "workflow_approvals" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_WORKFLOW_APPROVAL_STATUS" ON "workflow_approvals" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_WORKFLOW_APPROVAL_REVIEWER" ON "workflow_approvals" ("reviewerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_WORKFLOW_APPROVAL_STAGE" ON "workflow_approvals" ("workflowStageId") `);
        await queryRunner.query(`CREATE TYPE "public"."workflow_stages_type_enum" AS ENUM('initiation', 'planning', 'execution', 'monitoring', 'closure', 'sprint', 'review', 'retrospective', 'custom')`);
        await queryRunner.query(`CREATE TYPE "public"."workflow_stages_status_enum" AS ENUM('active', 'inactive', 'deprecated')`);
        await queryRunner.query(`CREATE TABLE "workflow_stages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workflowTemplateId" uuid NOT NULL, "name" character varying(255) NOT NULL, "description" text, "type" "public"."workflow_stages_type_enum" NOT NULL DEFAULT 'custom', "status" "public"."workflow_stages_status_enum" NOT NULL DEFAULT 'active', "order" integer NOT NULL, "estimatedDuration" integer NOT NULL DEFAULT '1', "durationUnit" character varying(50) NOT NULL DEFAULT 'days', "entryCriteria" jsonb NOT NULL DEFAULT '{}', "exitCriteria" jsonb NOT NULL DEFAULT '{}', "deliverables" jsonb NOT NULL DEFAULT '{}', "roles" jsonb NOT NULL DEFAULT '{}', "raciMatrix" jsonb NOT NULL DEFAULT '{}', "requiresApproval" boolean NOT NULL DEFAULT false, "isMilestone" boolean NOT NULL DEFAULT false, "dependencies" jsonb NOT NULL DEFAULT '{}', "metadata" jsonb NOT NULL DEFAULT '{}', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "PK_a521b91fac23874e5750cbeccb2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_WORKFLOW_STAGE_STATUS" ON "workflow_stages" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_WORKFLOW_STAGE_TYPE" ON "workflow_stages" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_WORKFLOW_STAGE_ORDER" ON "workflow_stages" ("workflowTemplateId", "order") `);
        await queryRunner.query(`CREATE INDEX "IDX_WORKFLOW_STAGE_TEMPLATE" ON "workflow_stages" ("workflowTemplateId") `);
        await queryRunner.query(`CREATE TABLE "resource_conflicts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "resourceId" character varying NOT NULL, "conflictDate" date NOT NULL, "totalAllocation" numeric(5,2) NOT NULL, "affectedProjects" jsonb NOT NULL, "severity" character varying NOT NULL, "resolved" boolean NOT NULL DEFAULT false, "detectedAt" TIMESTAMP NOT NULL DEFAULT now(), "resolvedAt" TIMESTAMP, CONSTRAINT "PK_0972038bcc2e54626f97d8e5d54" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6ffdb745d89e02fbe2134a33a5" ON "resource_conflicts" ("severity") `);
        await queryRunner.query(`CREATE INDEX "IDX_a0bddfb3573a2b4c68cae63be1" ON "resource_conflicts" ("resourceId", "conflictDate") `);
        await queryRunner.query(`CREATE TYPE "public"."roles_name_enum" AS ENUM('admin', 'editor', 'viewer', 'project_manager', 'developer', 'analyst')`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" "public"."roles_name_enum" NOT NULL, "description" character varying(500), "permissions" json, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_648e3f5447f725579d7d4ffdfb7" UNIQUE ("name"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ROLE_NAME" ON "roles" ("name") `);
        await queryRunner.query(`CREATE TABLE "team_members" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "team_id" uuid NOT NULL, "user_id" uuid NOT NULL, "role_id" uuid NOT NULL, "organizationId" uuid NOT NULL, "joinedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ca3eae89dcf20c9fd95bf7460aa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_TEAM_MEMBER_UNIQUE" ON "team_members" ("team_id", "user_id") `);
        await queryRunner.query(`CREATE TABLE "teams" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "description" text, "project_id" uuid NOT NULL, "organizationId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_14902fb0ff165d2b8c249b5425" UNIQUE ("project_id"), CONSTRAINT "PK_7e5523774a38b08a6236d322403" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "project_risks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "projectId" uuid NOT NULL, "riskDescription" text NOT NULL, "category" character varying(100), "probability" character varying(20), "impact" character varying(20), "riskScore" numeric(3,1), "mitigationStrategy" text, "owner" character varying(100), "status" character varying(50) NOT NULL DEFAULT 'identified', "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP, CONSTRAINT "PK_6a3d2c8ce5a1d7e807acb7a320e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_70b83a30fc8a2d5a59e3a702ed" ON "project_risks" ("projectId", "riskScore") `);
        await queryRunner.query(`CREATE TABLE "project_stakeholders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "projectId" uuid NOT NULL, "name" character varying(200) NOT NULL, "role" character varying(100), "organization" character varying(200), "influence" character varying(20), "interest" character varying(20), "category" character varying(100), "communicationPreference" character varying(100), "engagementStrategy" text, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP, CONSTRAINT "PK_7d0a1e00368411e2e958e8cb24b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_fee3e62124842d117f5f425d3a" ON "project_stakeholders" ("projectId", "influence", "interest") `);
        await queryRunner.query(`CREATE TABLE "user_projects" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "organizationId" uuid NOT NULL, "name" character varying(200) NOT NULL, "description" text, "methodology" character varying(20), "status" character varying(50) NOT NULL DEFAULT 'planning', "startDate" date, "targetEndDate" date, "budget" numeric(12,2), "portfolioId" uuid, "programId" uuid, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP, CONSTRAINT "PK_3d2a17149b660c4f9183241b911" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_fc694bf852ad3894693c3046e5" ON "user_projects" ("portfolioId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ea733ff193912a2ec4dc294dc6" ON "user_projects" ("userId", "status") `);
        await queryRunner.query(`CREATE TABLE "project_tasks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "projectId" uuid NOT NULL, "parentTaskId" uuid, "name" character varying(200) NOT NULL, "description" text, "status" character varying(50) NOT NULL DEFAULT 'pending', "assignedTo" character varying(100), "estimatedHours" numeric(8,2), "actualHours" numeric(8,2), "priority" character varying(20) NOT NULL DEFAULT 'medium', "dueDate" date, "dependencies" text array NOT NULL DEFAULT '{}', "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP, CONSTRAINT "PK_b1b6204912a6f44133df3a4518b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ef7da82084d0de2927d7f95579" ON "project_tasks" ("parentTaskId") `);
        await queryRunner.query(`CREATE INDEX "IDX_fdba7c2e9f191ed27416475913" ON "project_tasks" ("projectId", "status") `);
        await queryRunner.query(`CREATE TABLE "resource_allocations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "resourceId" uuid NOT NULL, "projectId" uuid NOT NULL, "taskId" uuid, "startDate" date NOT NULL, "endDate" date NOT NULL, "allocationPercentage" numeric(5,2) NOT NULL, "hoursPerDay" integer NOT NULL DEFAULT '8', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e689823b7f4c8674823327a80b5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ee0c5b6e142c99abdebfaf4b07" ON "resource_allocations" ("projectId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b8b247beebde4bcd470d1b0272" ON "resource_allocations" ("resourceId", "startDate", "endDate") `);
        await queryRunner.query(`CREATE TYPE "public"."workflow_instances_status_enum" AS ENUM('active', 'completed', 'cancelled', 'on_hold', 'failed')`);
        await queryRunner.query(`CREATE TYPE "public"."workflow_instances_priority_enum" AS ENUM('low', 'medium', 'high', 'critical')`);
        await queryRunner.query(`CREATE TABLE "workflow_instances" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organizationId" uuid NOT NULL, "templateId" uuid NOT NULL, "title" character varying NOT NULL, "description" text, "status" "public"."workflow_instances_status_enum" NOT NULL DEFAULT 'active', "currentStage" character varying, "data" jsonb NOT NULL DEFAULT '{}', "stageHistory" jsonb NOT NULL DEFAULT '[]', "approvals" jsonb NOT NULL DEFAULT '[]', "assignedTo" uuid, "createdBy" uuid NOT NULL, "dueDate" date, "priority" "public"."workflow_instances_priority_enum" NOT NULL DEFAULT 'medium', "metadata" jsonb NOT NULL DEFAULT '{}', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_90cc94e44ff8b7b7869f50e4fc4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "stakeholder_communications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "projectId" uuid NOT NULL, "stakeholderType" character varying(50) NOT NULL, "stakeholderName" character varying(255) NOT NULL, "communicationDate" date NOT NULL, "communicationType" character varying(100) NOT NULL, "subject" character varying(255) NOT NULL, "content" text NOT NULL, "deliveryMetrics" jsonb, "attachments" text array, "status" character varying(20) NOT NULL, "sentBy" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_caa36e49fad051b40381f0f03d2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_794f6f83be3de83a3e0de0a54e" ON "stakeholder_communications" ("communicationDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_dbcadb4fdd56e827cdeb5b9fb0" ON "stakeholder_communications" ("projectId", "stakeholderType") `);
        await queryRunner.query(`CREATE TABLE "risk_responses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "riskId" uuid NOT NULL, "strategy" "public"."risk_responses_strategy_enum" NOT NULL, "rationale" text NOT NULL, "description" text, "actions" jsonb NOT NULL, "contingencyPlan" jsonb, "transferDetails" jsonb, "monitoring" jsonb NOT NULL, "effectiveness" jsonb, "status" "public"."risk_responses_status_enum" NOT NULL DEFAULT 'draft', "approvedDate" date, "approvedBy" uuid, "implementationDate" date, "completedDate" date, "responseData" jsonb, "createdBy" uuid NOT NULL, "lastUpdatedBy" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_12879569ceeddc16e5085fe30fd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d9a623e83e18b6124bc8383a9c" ON "risk_responses" ("createdAt", "strategy") `);
        await queryRunner.query(`CREATE INDEX "IDX_63ab5d4c8681a58d0bc079f7ef" ON "risk_responses" ("riskId", "strategy") `);
        await queryRunner.query(`CREATE TABLE "risk_monitoring" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "riskId" uuid NOT NULL, "monitoringDate" date NOT NULL, "monitoringFrequency" "public"."risk_monitoring_monitoringfrequency_enum" NOT NULL DEFAULT 'weekly', "kpis" jsonb NOT NULL, "monitoringData" jsonb NOT NULL, "alertLevel" "public"."risk_monitoring_alertlevel_enum" NOT NULL DEFAULT 'none', "alertStatus" "public"."risk_monitoring_alertstatus_enum", "alertDescription" text, "alertActions" jsonb, "updatedProbability" numeric(3,1), "updatedImpact" numeric(3,1), "assessmentChanges" text, "recommendedActions" text, "assignedTo" uuid NOT NULL, "reviewedBy" uuid, "reviewedAt" TIMESTAMP, "reviewNotes" text, "nextMonitoringDate" date NOT NULL, "escalationRequired" boolean NOT NULL DEFAULT false, "escalationReason" text, "createdBy" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_fdb722735544659aadb4fca5647" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_fc12ad4a736f87e96c0bcde08c" ON "risk_monitoring" ("alertStatus", "monitoringDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_58908332becb66d6d747a27890" ON "risk_monitoring" ("riskId", "monitoringDate") `);
        await queryRunner.query(`CREATE TABLE "risks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "projectId" uuid NOT NULL, "organizationId" uuid NOT NULL, "title" character varying(255) NOT NULL, "description" text NOT NULL, "category" "public"."risks_category_enum" NOT NULL, "subcategory" character varying(100), "probability" numeric(3,1) NOT NULL, "impact" numeric(3,1) NOT NULL, "impactBreakdown" jsonb NOT NULL, "riskScore" numeric(4,1) NOT NULL, "riskLevel" "public"."risks_risklevel_enum" NOT NULL, "status" "public"."risks_status_enum" NOT NULL DEFAULT 'identified', "statusNotes" text, "assignedTo" uuid, "expectedOccurrence" date, "closedDate" date, "scheduleImpactDays" integer, "budgetImpactAmount" numeric(12,2), "scopeImpactPercent" numeric(5,2), "qualityImpactDescription" text, "triggers" jsonb NOT NULL, "dependencies" jsonb, "source" "public"."risks_source_enum" NOT NULL DEFAULT 'manual-entry', "confidence" numeric(5,2) NOT NULL DEFAULT '100', "probabilityRationale" text, "evidencePoints" jsonb, "riskData" jsonb NOT NULL, "createdBy" uuid NOT NULL, "lastUpdatedBy" uuid, "lastAssessmentDate" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_df437126f5dd05e856b8bf7157f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_368b6a4812773a963dd41870b5" ON "risks" ("createdAt", "riskScore") `);
        await queryRunner.query(`CREATE INDEX "IDX_ade258af0181b62af135447cd4" ON "risks" ("category", "riskLevel") `);
        await queryRunner.query(`CREATE INDEX "IDX_bf6329856d9a15a3504987f109" ON "risks" ("projectId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_9966ac1c65e05c4c9f5582d76e" ON "risks" ("projectId", "riskLevel") `);
        await queryRunner.query(`CREATE TABLE "risk_assessments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "projectId" uuid NOT NULL, "assessmentDate" date NOT NULL, "assessmentType" "public"."risk_assessments_assessmenttype_enum" NOT NULL, "assessmentTrigger" text, "assessmentScope" jsonb NOT NULL, "assessmentResults" jsonb NOT NULL, "analysisSummary" jsonb NOT NULL, "recommendations" jsonb NOT NULL, "aiAnalysis" jsonb, "stakeholderInput" jsonb NOT NULL, "assessmentQuality" jsonb NOT NULL, "nextAssessmentDate" date, "followUpActions" jsonb, "conductedBy" uuid NOT NULL, "reviewedBy" uuid, "reviewedAt" TIMESTAMP, "status" "public"."risk_assessments_status_enum" NOT NULL DEFAULT 'draft', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2717ff3f294d30390a712653d63" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_36705f77192f2a56e9e04880f8" ON "risk_assessments" ("assessmentType", "assessmentDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_f47ac4f55eb44910c5fca837bc" ON "risk_assessments" ("projectId", "assessmentDate") `);
        await queryRunner.query(`CREATE TABLE "waitlist" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "email" character varying NOT NULL, "biggestChallenge" text, "emailVerified" boolean NOT NULL DEFAULT false, "company" character varying, "source" character varying, "status" character varying NOT NULL DEFAULT 'pending', "invitedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_2221cffeeb64bff14201bd5b3de" UNIQUE ("email"), CONSTRAINT "PK_973cfbedc6381485681d6a6916c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2221cffeeb64bff14201bd5b3d" ON "waitlist" ("email") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_2221cffeeb64bff14201bd5b3d" ON "waitlist" ("email") `);
        await queryRunner.query(`CREATE TABLE "project_metrics" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "projectId" uuid NOT NULL, "metricDate" date NOT NULL, "metricType" character varying(100) NOT NULL, "metricCategory" character varying(100) NOT NULL, "metricValue" numeric(10,4) NOT NULL, "metricUnit" character varying(20), "metricMetadata" jsonb, "notes" text, "recordedBy" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d8c0eade2962fbd94e56f8dce97" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_569ac3c1447351deafa2db09f5" ON "project_metrics" ("metricType") `);
        await queryRunner.query(`CREATE INDEX "IDX_846a162364072ebfbecd514622" ON "project_metrics" ("projectId", "metricDate") `);
        await queryRunner.query(`CREATE TABLE "programs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "organizationId" uuid NOT NULL, "name" character varying(200) NOT NULL, "description" text, "status" character varying(50) NOT NULL DEFAULT 'initiating', "totalBudget" numeric(12,2), "startDate" date, "endDate" date, "benefits" jsonb, "dependencies" jsonb, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP, CONSTRAINT "PK_d43c664bcaafc0e8a06dfd34e05" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a99b3ca19aedd64a3f069cdeac" ON "programs" ("userId") `);
        await queryRunner.query(`CREATE TABLE "performance_baselines" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "projectId" uuid NOT NULL, "baselineType" character varying(50) NOT NULL, "baselineDate" date NOT NULL, "version" integer NOT NULL, "baselineData" jsonb NOT NULL, "changeReason" text, "approvedBy" uuid NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4d646788ef80330072be21534bc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_88e460cb86118c8e0f42c93fd1" ON "performance_baselines" ("projectId", "baselineType") `);
        await queryRunner.query(`CREATE TYPE "public"."manual_updates_category_enum" AS ENUM('schedule', 'budget', 'scope', 'quality', 'risk', 'stakeholder')`);
        await queryRunner.query(`CREATE TYPE "public"."manual_updates_impact_enum" AS ENUM('positive', 'negative', 'neutral')`);
        await queryRunner.query(`CREATE TABLE "manual_updates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "projectId" uuid NOT NULL, "organizationId" uuid NOT NULL, "category" "public"."manual_updates_category_enum" NOT NULL, "description" text NOT NULL, "impact" "public"."manual_updates_impact_enum" NOT NULL, "quantitativeData" jsonb, "attachments" text array, "reviewStatus" jsonb, "includedInReport" boolean NOT NULL DEFAULT false, "submittedBy" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_274f77638c8b4b11140c9b855dc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_44d4dd46e432e62217f8bced6f" ON "manual_updates" ("impact") `);
        await queryRunner.query(`CREATE INDEX "IDX_e937b8b9c7c08129635cbcca12" ON "manual_updates" ("category") `);
        await queryRunner.query(`CREATE INDEX "IDX_89d3ac584e2551f507bf9730c9" ON "manual_updates" ("projectId", "createdAt") `);
        await queryRunner.query(`CREATE TABLE "portfolios" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "organizationId" uuid NOT NULL, "name" character varying(200) NOT NULL, "description" text, "status" character varying(50) NOT NULL DEFAULT 'active', "totalBudget" numeric(12,2), "startDate" date, "endDate" date, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP, CONSTRAINT "PK_488aa6e9b219d1d9087126871ae" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e4e66691a2634fcf5525e33ecf" ON "portfolios" ("userId") `);
        await queryRunner.query(`CREATE TABLE "intake_forms" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organizationId" uuid NOT NULL, "name" character varying NOT NULL, "slug" character varying NOT NULL, "description" text, "thankYouMessage" text, "formSchema" jsonb NOT NULL, "targetWorkflowId" uuid, "isPublic" boolean NOT NULL DEFAULT true, "isActive" boolean NOT NULL DEFAULT true, "settings" jsonb NOT NULL DEFAULT '{}', "analytics" jsonb NOT NULL DEFAULT '{}', "aiGenerationContext" jsonb, "intelligentFeatures" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_77c31beedd4015fd12cf210050b" UNIQUE ("slug"), CONSTRAINT "PK_5aa0e78d4589808303905892830" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_intake_form_slug" ON "intake_forms" ("slug") `);
        await queryRunner.query(`CREATE TYPE "public"."intake_submissions_status_enum" AS ENUM('pending', 'processing', 'processed', 'rejected', 'cancelled')`);
        await queryRunner.query(`CREATE TYPE "public"."intake_submissions_priority_enum" AS ENUM('low', 'medium', 'high', 'urgent')`);
        await queryRunner.query(`CREATE TABLE "intake_submissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organizationId" uuid NOT NULL, "formId" uuid NOT NULL, "title" character varying NOT NULL, "description" text, "status" "public"."intake_submissions_status_enum" NOT NULL DEFAULT 'pending', "data" jsonb NOT NULL, "submitterName" character varying, "submitterEmail" character varying, "submitterPhone" character varying, "submittedBy" uuid, "assignedTo" uuid, "processedBy" uuid, "processedAt" TIMESTAMP, "processingNotes" text, "workflowInstanceId" uuid, "priority" "public"."intake_submissions_priority_enum" NOT NULL DEFAULT 'medium', "tags" jsonb NOT NULL DEFAULT '[]', "dueDate" date, "automationResults" jsonb NOT NULL DEFAULT '{}', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_17598a9705945181d87b93544e0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_intake_submission_created_at" ON "intake_submissions" ("createdAt") `);
        await queryRunner.query(`CREATE TABLE "alert_configurations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "projectId" uuid NOT NULL, "alertType" character varying(100) NOT NULL, "threshold" numeric(5,2) NOT NULL, "operator" character varying(20) NOT NULL, "severity" character varying(20) NOT NULL, "notificationChannels" jsonb NOT NULL, "recipients" jsonb NOT NULL, "customMessage" text, "isActive" boolean NOT NULL DEFAULT true, "createdBy" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_87c580711f2b1caa0f82529d71c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e09e2891fd32efaa2ca5234595" ON "alert_configurations" ("projectId") `);
        await queryRunner.query(`CREATE TABLE "pm_knowledge_chunks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organizationId" uuid, "content" text NOT NULL, "domain" character varying(50) NOT NULL, "subdomain" character varying(100), "methodology" character varying(20) NOT NULL, "processGroup" character varying(50), "embedding" text, "source" character varying(200) NOT NULL DEFAULT 'Rita_Mulcahy_PMP_11th_Ed', "confidence" numeric(3,2) NOT NULL DEFAULT '1', "applicability" text array NOT NULL DEFAULT '{}', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a9af631b9a4571e627005692dca" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7f21464383479f9b76665c08b1" ON "pm_knowledge_chunks" ("methodology", "processGroup") `);
        await queryRunner.query(`CREATE INDEX "IDX_d89232e343acb658781b906c62" ON "pm_knowledge_chunks" ("domain", "subdomain") `);
        await queryRunner.query(`CREATE TYPE "public"."invitations_role_enum" AS ENUM('admin', 'pm', 'viewer')`);
        await queryRunner.query(`CREATE TYPE "public"."invitations_status_enum" AS ENUM('pending', 'accepted', 'expired', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "invitations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "token" character varying NOT NULL, "email" character varying NOT NULL, "role" "public"."invitations_role_enum" NOT NULL, "status" "public"."invitations_status_enum" NOT NULL DEFAULT 'pending', "message" text, "expiresAt" TIMESTAMP NOT NULL, "acceptedAt" TIMESTAMP, "organizationId" uuid NOT NULL, "invitedByUserId" uuid NOT NULL, "acceptedByUserId" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_e577dcf9bb6d084373ed3998509" UNIQUE ("token"), CONSTRAINT "PK_5dec98cfdfd562e4ad3648bbb07" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_INVITATION_EXPIRES" ON "invitations" ("expiresAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_INVITATION_STATUS" ON "invitations" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_INVITATION_EMAIL_ORG" ON "invitations" ("email", "organizationId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_INVITATION_TOKEN" ON "invitations" ("token") `);
        await queryRunner.query(`CREATE TYPE "public"."feedback_type_enum" AS ENUM('bug', 'feature_request', 'usability', 'general')`);
        await queryRunner.query(`CREATE TYPE "public"."feedback_status_enum" AS ENUM('new', 'reviewing', 'acknowledged', 'implemented', 'closed')`);
        await queryRunner.query(`CREATE TABLE "feedback" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" "public"."feedback_type_enum" NOT NULL DEFAULT 'general', "content" text NOT NULL, "context" text, "status" "public"."feedback_status_enum" NOT NULL DEFAULT 'new', "metadata" json, "user_id" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8389f9e087a57689cd5be8b2b13" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_FEEDBACK_STATUS" ON "feedback" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_FEEDBACK_TYPE" ON "feedback" ("type") `);
        await queryRunner.query(`CREATE TYPE "public"."email_verifications_status_enum" AS ENUM('pending', 'verified', 'expired')`);
        await queryRunner.query(`CREATE TABLE "email_verifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "token" character varying NOT NULL, "email" character varying NOT NULL, "userId" uuid NOT NULL, "status" "public"."email_verifications_status_enum" NOT NULL DEFAULT 'pending', "expiresAt" TIMESTAMP NOT NULL, "verifiedAt" TIMESTAMP, "ipAddress" inet, "userAgent" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_595be4c36e66b21d3fd14c73a24" UNIQUE ("token"), CONSTRAINT "PK_c1ea2921e767f83cd44c0af203f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_EMAIL_VERIFICATION_EXPIRES" ON "email_verifications" ("expiresAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_EMAIL_VERIFICATION_USER" ON "email_verifications" ("userId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_EMAIL_VERIFICATION_TOKEN" ON "email_verifications" ("token") `);
        await queryRunner.query(`CREATE TYPE "public"."generated_project_plans_methodology_enum" AS ENUM('waterfall', 'agile', 'hybrid')`);
        await queryRunner.query(`CREATE TABLE "generated_project_plans" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "brdAnalysisId" uuid NOT NULL, "organizationId" uuid NOT NULL, "methodology" "public"."generated_project_plans_methodology_enum" NOT NULL, "planStructure" jsonb NOT NULL, "resourcePlan" jsonb NOT NULL, "riskRegister" jsonb NOT NULL, "generationMetadata" jsonb NOT NULL, "changesMade" jsonb, "generatedBy" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8dbd4449826bf9b964e48c5e438" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6e1d50e5619fc3bcddf713822f" ON "generated_project_plans" ("generatedBy") `);
        await queryRunner.query(`CREATE INDEX "IDX_fb450c1b3ed4ccfad85376966f" ON "generated_project_plans" ("methodology") `);
        await queryRunner.query(`CREATE INDEX "IDX_9516a203d3479f155a56ff27d3" ON "generated_project_plans" ("organizationId", "brdAnalysisId") `);
        await queryRunner.query(`CREATE TABLE "brd_analyses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "brdId" uuid NOT NULL, "organizationId" uuid NOT NULL, "extractedElements" jsonb NOT NULL, "analysisMetadata" jsonb NOT NULL, "analyzedBy" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d488a1b638d41f93b6d6416bf1c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0da62e1a1027d022c32eff7390" ON "brd_analyses" ("analyzedBy") `);
        await queryRunner.query(`CREATE INDEX "IDX_f0b43298945e948fa331ce0d9c" ON "brd_analyses" ("organizationId", "brdId") `);
        await queryRunner.query(`CREATE TYPE "public"."brds_status_enum" AS ENUM('draft', 'in_review', 'approved', 'published')`);
        await queryRunner.query(`CREATE TABLE "brds" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organizationId" uuid NOT NULL, "project_id" uuid, "version" integer NOT NULL DEFAULT '1', "status" "public"."brds_status_enum" NOT NULL DEFAULT 'draft', "payload" jsonb NOT NULL, "search_vector" tsvector, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_31f5a892cd53cd8dee10731bce5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0728e1c945a83b0366c9f96c34" ON "brds" ("organizationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_2bf3b4f13cdf45dd0e66d39c88" ON "brds" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_8191cd6f05e030fa59f7c1ed69" ON "brds" ("organizationId", "project_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_7b356132417fe2de0d091a0c67" ON "brds" ("organizationId", "status") `);
        await queryRunner.query(`CREATE TYPE "public"."ai_analyses_type_enum" AS ENUM('brd_analysis', 'requirement_extraction', 'risk_assessment', 'dependency_mapping', 'cost_estimation', 'timeline_analysis')`);
        await queryRunner.query(`CREATE TYPE "public"."ai_analyses_status_enum" AS ENUM('pending', 'processing', 'completed', 'failed', 'cancelled')`);
        await queryRunner.query(`CREATE TYPE "public"."ai_analyses_confidencelevel_enum" AS ENUM('low', 'medium', 'high', 'very_high')`);
        await queryRunner.query(`CREATE TABLE "ai_analyses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organizationId" uuid NOT NULL, "userId" uuid NOT NULL, "documentName" character varying(255) NOT NULL, "documentHash" character varying(64) NOT NULL, "documentType" character varying(100) NOT NULL, "documentSize" bigint NOT NULL, "type" "public"."ai_analyses_type_enum" NOT NULL DEFAULT 'brd_analysis', "status" "public"."ai_analyses_status_enum" NOT NULL DEFAULT 'pending', "confidenceLevel" "public"."ai_analyses_confidencelevel_enum", "confidenceScore" numeric(5,2), "processingTimeMs" integer, "analysisResult" jsonb NOT NULL DEFAULT '{}', "metadata" jsonb NOT NULL DEFAULT '{}', "processingOptions" jsonb NOT NULL DEFAULT '{}', "startedAt" TIMESTAMP, "completedAt" TIMESTAMP, "failedAt" TIMESTAMP, "retryCount" integer NOT NULL DEFAULT '0', "nextRetryAt" TIMESTAMP, "totalCost" numeric(10,4) NOT NULL DEFAULT '0', "costCurrency" character varying(3) NOT NULL DEFAULT 'USD', "auditTrail" jsonb NOT NULL DEFAULT '{}', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "UQ_43a04aef207fe24869c3faf659c" UNIQUE ("documentHash"), CONSTRAINT "PK_f668f96ca6b8cd3dd8ebbd5c576" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_AI_ANALYSIS_COMPOSITE" ON "ai_analyses" ("organizationId", "status", "type") `);
        await queryRunner.query(`CREATE INDEX "IDX_AI_ANALYSIS_DOCUMENT_HASH" ON "ai_analyses" ("documentHash") `);
        await queryRunner.query(`CREATE INDEX "IDX_AI_ANALYSIS_CREATED_AT" ON "ai_analyses" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_AI_ANALYSIS_TYPE" ON "ai_analyses" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_AI_ANALYSIS_STATUS" ON "ai_analyses" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_AI_ANALYSIS_USER" ON "ai_analyses" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_AI_ANALYSIS_ORGANIZATION" ON "ai_analyses" ("organizationId") `);
        await queryRunner.query(`CREATE TABLE "status_reports" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "project_id" uuid NOT NULL, "organization_id" uuid, "report_date" date NOT NULL, "reporting_period_start" date NOT NULL, "reporting_period_end" date NOT NULL, "overall_status" character varying NOT NULL, "overall_health_score" numeric(5,2) NOT NULL, "stakeholder_audience" character varying NOT NULL, "report_format" character varying NOT NULL, "report_data" jsonb, "schedule_variance" numeric(5,2), "budget_variance" numeric(5,2), "scope_completion" numeric(5,2), "active_risks" integer, "critical_risks" integer, "cost_performance_index" numeric(5,2), "schedule_performance_index" numeric(5,2), "created_by" uuid, "summary" text NOT NULL, "accomplishments" text NOT NULL, "challenges" text NOT NULL, "next_steps" text NOT NULL, "risks_issues" text NOT NULL, "schedule_performance" numeric(5,2) NOT NULL, "budget_performance" numeric(5,2) NOT NULL, "scope_performance" numeric(5,2) NOT NULL, "quality_performance" numeric(5,2) NOT NULL, "resource_performance" numeric(5,2) NOT NULL, "stakeholder_satisfaction" numeric(5,2) NOT NULL, "team_satisfaction" numeric(5,2) NOT NULL, "notes" text NOT NULL, "reported_by_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5b303afd85233dce17c88c519ca" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "updated_at"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_WORKFLOW_TEMPLATE_CREATED_BY"`);
        await queryRunner.query(`ALTER TABLE "workflow_templates" DROP COLUMN "createdBy"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_WORKFLOW_TEMPLATE_STATUS"`);
        await queryRunner.query(`ALTER TABLE "workflow_templates" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "workflow_templates" DROP COLUMN "version"`);
        await queryRunner.query(`ALTER TABLE "workflow_templates" DROP COLUMN "tags"`);
        await queryRunner.query(`ALTER TABLE "workflow_templates" DROP COLUMN "usageCount"`);
        await queryRunner.query(`ALTER TABLE "workflow_templates" DROP COLUMN "lastUsedAt"`);
        await queryRunner.query(`ALTER TABLE "workflow_templates" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "organizations" ADD "settings" jsonb NOT NULL DEFAULT '{}'`);
        await queryRunner.query(`CREATE TYPE "public"."organizations_status_enum" AS ENUM('active', 'suspended', 'trial')`);
        await queryRunner.query(`ALTER TABLE "organizations" ADD "status" "public"."organizations_status_enum" NOT NULL DEFAULT 'active'`);
        await queryRunner.query(`ALTER TABLE "organizations" ADD "trialEndsAt" date`);
        await queryRunner.query(`ALTER TABLE "organizations" ADD "description" text`);
        await queryRunner.query(`ALTER TABLE "organizations" ADD "website" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "organizations" ADD "industry" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "organizations" ADD "size" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "workflow_templates" ADD "createdBy" uuid NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."workflow_templates_status_enum" AS ENUM('active', 'draft', 'archived', 'deprecated')`);
        await queryRunner.query(`ALTER TABLE "workflow_templates" ADD "status" "public"."workflow_templates_status_enum" NOT NULL DEFAULT 'draft'`);
        await queryRunner.query(`ALTER TABLE "workflow_templates" ADD "version" integer NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE "workflow_templates" ADD "tags" jsonb`);
        await queryRunner.query(`ALTER TABLE "workflow_templates" ADD "usageCount" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "workflow_templates" ADD "lastUsedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "workflow_templates" ADD "deletedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "workflow_templates" ADD "configuration" jsonb NOT NULL DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "workflow_templates" ADD "isActive" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "users_email_key"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "email" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "password"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "password" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "firstName"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "firstName" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "lastName"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "lastName" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "role"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "role" character varying NOT NULL DEFAULT 'user'`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "organizationId"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "organizationId" character varying`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "profilePicture"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "profilePicture" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "isActive" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "isEmailVerified" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "lastLogin"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "lastLogin" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "resetTokenExpiry"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "resetTokenExpiry" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "createdAt" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updatedAt" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "organizations" ADD CONSTRAINT "UQ_963693341bd612aa01ddf3a4b68" UNIQUE ("slug")`);
        await queryRunner.query(`ALTER TABLE "organizations" ALTER COLUMN "slug" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "organizations" ALTER COLUMN "createdAt" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "organizations" ALTER COLUMN "updatedAt" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "methodology"`);
        await queryRunner.query(`CREATE TYPE "public"."projects_methodology_enum" AS ENUM('Waterfall', 'Agile', 'Scrum')`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "methodology" "public"."projects_methodology_enum" NOT NULL DEFAULT 'Waterfall'`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."projects_status_enum" AS ENUM('planning', 'active', 'on-hold', 'completed', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "status" "public"."projects_status_enum" NOT NULL DEFAULT 'planning'`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "priority"`);
        await queryRunner.query(`CREATE TYPE "public"."projects_priority_enum" AS ENUM('low', 'medium', 'high', 'critical')`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "priority" "public"."projects_priority_enum" NOT NULL DEFAULT 'medium'`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "risk_level"`);
        await queryRunner.query(`CREATE TYPE "public"."projects_risk_level_enum" AS ENUM('low', 'medium', 'high', 'critical')`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "risk_level" "public"."projects_risk_level_enum" NOT NULL DEFAULT 'medium'`);
        await queryRunner.query(`ALTER TABLE "workflow_templates" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "workflow_templates" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."workflow_templates_type_enum" RENAME TO "workflow_templates_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."workflow_templates_type_enum" AS ENUM('intake', 'project', 'orr', 'custom')`);
        await queryRunner.query(`ALTER TABLE "workflow_templates" ALTER COLUMN "type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "workflow_templates" ALTER COLUMN "type" TYPE "public"."workflow_templates_type_enum" USING "type"::"text"::"public"."workflow_templates_type_enum"`);
        await queryRunner.query(`ALTER TABLE "workflow_templates" ALTER COLUMN "type" SET DEFAULT 'custom'`);
        await queryRunner.query(`DROP TYPE "public"."workflow_templates_type_enum_old"`);
        await queryRunner.query(`CREATE INDEX "IDX_ORGANIZATION_STATUS" ON "organizations" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_ORGANIZATION_SLUG" ON "organizations" ("slug") `);
        await queryRunner.query(`CREATE INDEX "IDX_WORKFLOW_TEMPLATE_CREATED_BY" ON "workflow_templates" ("createdBy") `);
        await queryRunner.query(`CREATE INDEX "IDX_WORKFLOW_TEMPLATE_STATUS" ON "workflow_templates" ("status") `);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_610102b60fea1455310ccd299de" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_organizations" ADD CONSTRAINT "FK_11d4cd5202bd8914464f4bec379" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_organizations" ADD CONSTRAINT "FK_71997faba4726730e91d514138e" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workflow_versions" ADD CONSTRAINT "FK_a43f0e678fa8b77620207de78f7" FOREIGN KEY ("workflowTemplateId") REFERENCES "workflow_templates"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workflow_versions" ADD CONSTRAINT "FK_bc539da5392fd2ded04c4576091" FOREIGN KEY ("createdBy") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workflow_versions" ADD CONSTRAINT "FK_1c22866d70fc2f0159eb36dea6e" FOREIGN KEY ("publishedBy") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workflow_templates" ADD CONSTRAINT "FK_832e303ee037faf1221334f8787" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workflow_templates" ADD CONSTRAINT "FK_acad158133d53be1046ec811e1f" FOREIGN KEY ("createdBy") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workflow_approvals" ADD CONSTRAINT "FK_7ac8731767f89895a62159c5ea4" FOREIGN KEY ("workflowStageId") REFERENCES "workflow_stages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workflow_approvals" ADD CONSTRAINT "FK_2325a5a23d7648036e28175948a" FOREIGN KEY ("reviewerId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workflow_stages" ADD CONSTRAINT "FK_ba496b9340c978e5ba998bec4f4" FOREIGN KEY ("workflowTemplateId") REFERENCES "workflow_templates"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "team_members" ADD CONSTRAINT "FK_fdad7d5768277e60c40e01cdcea" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "team_members" ADD CONSTRAINT "FK_c2bf4967c8c2a6b845dadfbf3d4" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "team_members" ADD CONSTRAINT "FK_7a4dbecafed7033ca58a453a42e" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "team_members" ADD CONSTRAINT "FK_32285ad3f2978ced48105e21d2b" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teams" ADD CONSTRAINT "FK_858389ddeb0bd6c6bf4e323f91e" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teams" ADD CONSTRAINT "FK_14902fb0ff165d2b8c249b54252" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_c24760a4c22a838d6a8eb1fdc3a" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_risks" ADD CONSTRAINT "FK_f8e1e857c806d91d7b5162878e1" FOREIGN KEY ("projectId") REFERENCES "user_projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_stakeholders" ADD CONSTRAINT "FK_d30ae4b3d8a1cd65b168b7b44b1" FOREIGN KEY ("projectId") REFERENCES "user_projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_projects" ADD CONSTRAINT "FK_5a16c747009ab057e927305482e" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_projects" ADD CONSTRAINT "FK_8f5f60efe1ef2847c1f36302f1f" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_tasks" ADD CONSTRAINT "FK_8691c10b6396e041f4b6d48f8a0" FOREIGN KEY ("projectId") REFERENCES "user_projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_tasks" ADD CONSTRAINT "FK_ef7da82084d0de2927d7f95579c" FOREIGN KEY ("parentTaskId") REFERENCES "project_tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "resource_allocations" ADD CONSTRAINT "FK_a7424967660055a6e9f6f372fae" FOREIGN KEY ("resourceId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "resource_allocations" ADD CONSTRAINT "FK_ee0c5b6e142c99abdebfaf4b074" FOREIGN KEY ("projectId") REFERENCES "projects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "resource_allocations" ADD CONSTRAINT "FK_dd755dcb42d641f39f00acc54a0" FOREIGN KEY ("taskId") REFERENCES "project_tasks"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workflow_instances" ADD CONSTRAINT "FK_8b15ad8a1664a5637a6b4aea861" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workflow_instances" ADD CONSTRAINT "FK_d24ffb9ffbc6814ad1a008f4273" FOREIGN KEY ("templateId") REFERENCES "workflow_templates"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workflow_instances" ADD CONSTRAINT "FK_30a8b31ed47738aa89eefd507bc" FOREIGN KEY ("assignedTo") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workflow_instances" ADD CONSTRAINT "FK_50394eb590de339edc826789e9e" FOREIGN KEY ("createdBy") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stakeholder_communications" ADD CONSTRAINT "FK_12016b34e4ea00175453b46b934" FOREIGN KEY ("projectId") REFERENCES "projects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "risk_responses" ADD CONSTRAINT "FK_47564f43ba61849eb056b0a28d1" FOREIGN KEY ("riskId") REFERENCES "risks"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "risk_monitoring" ADD CONSTRAINT "FK_40dedce47af27af4c85ceed9fc4" FOREIGN KEY ("riskId") REFERENCES "risks"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "risks" ADD CONSTRAINT "FK_66af01342326330e1af6b50011d" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_metrics" ADD CONSTRAINT "FK_fa2d257aeb7e3ec72dc73148887" FOREIGN KEY ("projectId") REFERENCES "projects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "programs" ADD CONSTRAINT "FK_b6ba439df167770198a8b005a73" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "programs" ADD CONSTRAINT "FK_a99b3ca19aedd64a3f069cdeac2" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "performance_baselines" ADD CONSTRAINT "FK_60c1760dc20f8b3280e71dd13c6" FOREIGN KEY ("projectId") REFERENCES "projects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "manual_updates" ADD CONSTRAINT "FK_5085409b1a200d481556292a964" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "manual_updates" ADD CONSTRAINT "FK_96715c86614e44b1c2b09e379f7" FOREIGN KEY ("projectId") REFERENCES "projects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "portfolios" ADD CONSTRAINT "FK_f58124642197ff147f525bf4fdc" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "portfolios" ADD CONSTRAINT "FK_e4e66691a2634fcf5525e33ecf5" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "intake_forms" ADD CONSTRAINT "FK_9ab1cbea834be28e56d8d641e2b" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "intake_forms" ADD CONSTRAINT "FK_53c20e12b8c7a8faef2b9b8524c" FOREIGN KEY ("targetWorkflowId") REFERENCES "workflow_templates"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "intake_submissions" ADD CONSTRAINT "FK_ac10dcecd6832b76dfcac8df5ac" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "intake_submissions" ADD CONSTRAINT "FK_9b079a6e5f5522ac4c7627a0d37" FOREIGN KEY ("formId") REFERENCES "intake_forms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "intake_submissions" ADD CONSTRAINT "FK_4e2741b3c27cb5d5bcd32754eb3" FOREIGN KEY ("submittedBy") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "intake_submissions" ADD CONSTRAINT "FK_f04402d6d73378e8734ccfb8ef6" FOREIGN KEY ("assignedTo") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "intake_submissions" ADD CONSTRAINT "FK_a75809b9a96c14e71fa4b487068" FOREIGN KEY ("processedBy") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "intake_submissions" ADD CONSTRAINT "FK_4a0208bcea6de3987f2ac5e8e61" FOREIGN KEY ("workflowInstanceId") REFERENCES "workflow_instances"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "alert_configurations" ADD CONSTRAINT "FK_e09e2891fd32efaa2ca52345950" FOREIGN KEY ("projectId") REFERENCES "projects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pm_knowledge_chunks" ADD CONSTRAINT "FK_312b7ebeaa4cba3b149ece4a28b" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invitations" ADD CONSTRAINT "FK_b9139f00cebfadced76bca3084f" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invitations" ADD CONSTRAINT "FK_b7423cfb362a842b7ea0a3763b9" FOREIGN KEY ("invitedByUserId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invitations" ADD CONSTRAINT "FK_3722ea7511a7ce9235525c1daa3" FOREIGN KEY ("acceptedByUserId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "feedback" ADD CONSTRAINT "FK_121c67d42dd543cca0809f59901" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "email_verifications" ADD CONSTRAINT "FK_4e63a91e0a684b31496bd50733e" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "generated_project_plans" ADD CONSTRAINT "FK_592bce5f9a5809748c326febe7e" FOREIGN KEY ("brdAnalysisId") REFERENCES "brd_analyses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "brd_analyses" ADD CONSTRAINT "FK_121e2480a59af8a10436ab8ec98" FOREIGN KEY ("brdId") REFERENCES "brds"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ai_analyses" ADD CONSTRAINT "FK_6b78f62c3592a8c8e490039a432" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ai_analyses" ADD CONSTRAINT "FK_3b0d7a0603ba332b377b0c39ca4" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "ai_analyses" DROP CONSTRAINT "FK_3b0d7a0603ba332b377b0c39ca4"`);
        await queryRunner.query(`ALTER TABLE "ai_analyses" DROP CONSTRAINT "FK_6b78f62c3592a8c8e490039a432"`);
        await queryRunner.query(`ALTER TABLE "brd_analyses" DROP CONSTRAINT "FK_121e2480a59af8a10436ab8ec98"`);
        await queryRunner.query(`ALTER TABLE "generated_project_plans" DROP CONSTRAINT "FK_592bce5f9a5809748c326febe7e"`);
        await queryRunner.query(`ALTER TABLE "email_verifications" DROP CONSTRAINT "FK_4e63a91e0a684b31496bd50733e"`);
        await queryRunner.query(`ALTER TABLE "feedback" DROP CONSTRAINT "FK_121c67d42dd543cca0809f59901"`);
        await queryRunner.query(`ALTER TABLE "invitations" DROP CONSTRAINT "FK_3722ea7511a7ce9235525c1daa3"`);
        await queryRunner.query(`ALTER TABLE "invitations" DROP CONSTRAINT "FK_b7423cfb362a842b7ea0a3763b9"`);
        await queryRunner.query(`ALTER TABLE "invitations" DROP CONSTRAINT "FK_b9139f00cebfadced76bca3084f"`);
        await queryRunner.query(`ALTER TABLE "pm_knowledge_chunks" DROP CONSTRAINT "FK_312b7ebeaa4cba3b149ece4a28b"`);
        await queryRunner.query(`ALTER TABLE "alert_configurations" DROP CONSTRAINT "FK_e09e2891fd32efaa2ca52345950"`);
        await queryRunner.query(`ALTER TABLE "intake_submissions" DROP CONSTRAINT "FK_4a0208bcea6de3987f2ac5e8e61"`);
        await queryRunner.query(`ALTER TABLE "intake_submissions" DROP CONSTRAINT "FK_a75809b9a96c14e71fa4b487068"`);
        await queryRunner.query(`ALTER TABLE "intake_submissions" DROP CONSTRAINT "FK_f04402d6d73378e8734ccfb8ef6"`);
        await queryRunner.query(`ALTER TABLE "intake_submissions" DROP CONSTRAINT "FK_4e2741b3c27cb5d5bcd32754eb3"`);
        await queryRunner.query(`ALTER TABLE "intake_submissions" DROP CONSTRAINT "FK_9b079a6e5f5522ac4c7627a0d37"`);
        await queryRunner.query(`ALTER TABLE "intake_submissions" DROP CONSTRAINT "FK_ac10dcecd6832b76dfcac8df5ac"`);
        await queryRunner.query(`ALTER TABLE "intake_forms" DROP CONSTRAINT "FK_53c20e12b8c7a8faef2b9b8524c"`);
        await queryRunner.query(`ALTER TABLE "intake_forms" DROP CONSTRAINT "FK_9ab1cbea834be28e56d8d641e2b"`);
        await queryRunner.query(`ALTER TABLE "portfolios" DROP CONSTRAINT "FK_e4e66691a2634fcf5525e33ecf5"`);
        await queryRunner.query(`ALTER TABLE "portfolios" DROP CONSTRAINT "FK_f58124642197ff147f525bf4fdc"`);
        await queryRunner.query(`ALTER TABLE "manual_updates" DROP CONSTRAINT "FK_96715c86614e44b1c2b09e379f7"`);
        await queryRunner.query(`ALTER TABLE "manual_updates" DROP CONSTRAINT "FK_5085409b1a200d481556292a964"`);
        await queryRunner.query(`ALTER TABLE "performance_baselines" DROP CONSTRAINT "FK_60c1760dc20f8b3280e71dd13c6"`);
        await queryRunner.query(`ALTER TABLE "programs" DROP CONSTRAINT "FK_a99b3ca19aedd64a3f069cdeac2"`);
        await queryRunner.query(`ALTER TABLE "programs" DROP CONSTRAINT "FK_b6ba439df167770198a8b005a73"`);
        await queryRunner.query(`ALTER TABLE "project_metrics" DROP CONSTRAINT "FK_fa2d257aeb7e3ec72dc73148887"`);
        await queryRunner.query(`ALTER TABLE "risks" DROP CONSTRAINT "FK_66af01342326330e1af6b50011d"`);
        await queryRunner.query(`ALTER TABLE "risk_monitoring" DROP CONSTRAINT "FK_40dedce47af27af4c85ceed9fc4"`);
        await queryRunner.query(`ALTER TABLE "risk_responses" DROP CONSTRAINT "FK_47564f43ba61849eb056b0a28d1"`);
        await queryRunner.query(`ALTER TABLE "stakeholder_communications" DROP CONSTRAINT "FK_12016b34e4ea00175453b46b934"`);
        await queryRunner.query(`ALTER TABLE "workflow_instances" DROP CONSTRAINT "FK_50394eb590de339edc826789e9e"`);
        await queryRunner.query(`ALTER TABLE "workflow_instances" DROP CONSTRAINT "FK_30a8b31ed47738aa89eefd507bc"`);
        await queryRunner.query(`ALTER TABLE "workflow_instances" DROP CONSTRAINT "FK_d24ffb9ffbc6814ad1a008f4273"`);
        await queryRunner.query(`ALTER TABLE "workflow_instances" DROP CONSTRAINT "FK_8b15ad8a1664a5637a6b4aea861"`);
        await queryRunner.query(`ALTER TABLE "resource_allocations" DROP CONSTRAINT "FK_dd755dcb42d641f39f00acc54a0"`);
        await queryRunner.query(`ALTER TABLE "resource_allocations" DROP CONSTRAINT "FK_ee0c5b6e142c99abdebfaf4b074"`);
        await queryRunner.query(`ALTER TABLE "resource_allocations" DROP CONSTRAINT "FK_a7424967660055a6e9f6f372fae"`);
        await queryRunner.query(`ALTER TABLE "project_tasks" DROP CONSTRAINT "FK_ef7da82084d0de2927d7f95579c"`);
        await queryRunner.query(`ALTER TABLE "project_tasks" DROP CONSTRAINT "FK_8691c10b6396e041f4b6d48f8a0"`);
        await queryRunner.query(`ALTER TABLE "user_projects" DROP CONSTRAINT "FK_8f5f60efe1ef2847c1f36302f1f"`);
        await queryRunner.query(`ALTER TABLE "user_projects" DROP CONSTRAINT "FK_5a16c747009ab057e927305482e"`);
        await queryRunner.query(`ALTER TABLE "project_stakeholders" DROP CONSTRAINT "FK_d30ae4b3d8a1cd65b168b7b44b1"`);
        await queryRunner.query(`ALTER TABLE "project_risks" DROP CONSTRAINT "FK_f8e1e857c806d91d7b5162878e1"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_c24760a4c22a838d6a8eb1fdc3a"`);
        await queryRunner.query(`ALTER TABLE "teams" DROP CONSTRAINT "FK_14902fb0ff165d2b8c249b54252"`);
        await queryRunner.query(`ALTER TABLE "teams" DROP CONSTRAINT "FK_858389ddeb0bd6c6bf4e323f91e"`);
        await queryRunner.query(`ALTER TABLE "team_members" DROP CONSTRAINT "FK_32285ad3f2978ced48105e21d2b"`);
        await queryRunner.query(`ALTER TABLE "team_members" DROP CONSTRAINT "FK_7a4dbecafed7033ca58a453a42e"`);
        await queryRunner.query(`ALTER TABLE "team_members" DROP CONSTRAINT "FK_c2bf4967c8c2a6b845dadfbf3d4"`);
        await queryRunner.query(`ALTER TABLE "team_members" DROP CONSTRAINT "FK_fdad7d5768277e60c40e01cdcea"`);
        await queryRunner.query(`ALTER TABLE "workflow_stages" DROP CONSTRAINT "FK_ba496b9340c978e5ba998bec4f4"`);
        await queryRunner.query(`ALTER TABLE "workflow_approvals" DROP CONSTRAINT "FK_2325a5a23d7648036e28175948a"`);
        await queryRunner.query(`ALTER TABLE "workflow_approvals" DROP CONSTRAINT "FK_7ac8731767f89895a62159c5ea4"`);
        await queryRunner.query(`ALTER TABLE "workflow_templates" DROP CONSTRAINT "FK_acad158133d53be1046ec811e1f"`);
        await queryRunner.query(`ALTER TABLE "workflow_templates" DROP CONSTRAINT "FK_832e303ee037faf1221334f8787"`);
        await queryRunner.query(`ALTER TABLE "workflow_versions" DROP CONSTRAINT "FK_1c22866d70fc2f0159eb36dea6e"`);
        await queryRunner.query(`ALTER TABLE "workflow_versions" DROP CONSTRAINT "FK_bc539da5392fd2ded04c4576091"`);
        await queryRunner.query(`ALTER TABLE "workflow_versions" DROP CONSTRAINT "FK_a43f0e678fa8b77620207de78f7"`);
        await queryRunner.query(`ALTER TABLE "user_organizations" DROP CONSTRAINT "FK_71997faba4726730e91d514138e"`);
        await queryRunner.query(`ALTER TABLE "user_organizations" DROP CONSTRAINT "FK_11d4cd5202bd8914464f4bec379"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "FK_610102b60fea1455310ccd299de"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_WORKFLOW_TEMPLATE_STATUS"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_WORKFLOW_TEMPLATE_CREATED_BY"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ORGANIZATION_SLUG"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ORGANIZATION_STATUS"`);
        await queryRunner.query(`CREATE TYPE "public"."workflow_templates_type_enum_old" AS ENUM('waterfall', 'agile', 'hybrid', 'custom')`);
        await queryRunner.query(`ALTER TABLE "workflow_templates" ALTER COLUMN "type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "workflow_templates" ALTER COLUMN "type" TYPE "public"."workflow_templates_type_enum_old" USING "type"::"text"::"public"."workflow_templates_type_enum_old"`);
        await queryRunner.query(`ALTER TABLE "workflow_templates" ALTER COLUMN "type" SET DEFAULT 'custom'`);
        await queryRunner.query(`DROP TYPE "public"."workflow_templates_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."workflow_templates_type_enum_old" RENAME TO "workflow_templates_type_enum"`);
        await queryRunner.query(`ALTER TABLE "workflow_templates" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "workflow_templates" ADD "name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "risk_level"`);
        await queryRunner.query(`DROP TYPE "public"."projects_risk_level_enum"`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "risk_level" character varying(20) DEFAULT 'medium'`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "priority"`);
        await queryRunner.query(`DROP TYPE "public"."projects_priority_enum"`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "priority" character varying(20) DEFAULT 'medium'`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."projects_status_enum"`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "status" character varying(20) DEFAULT 'planning'`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "methodology"`);
        await queryRunner.query(`DROP TYPE "public"."projects_methodology_enum"`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "methodology" character varying(20) DEFAULT 'Waterfall'`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "organizations" ALTER COLUMN "updatedAt" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "organizations" ALTER COLUMN "createdAt" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "organizations" ALTER COLUMN "slug" SET DEFAULT ('org-'|| gen_random_uuid())`);
        await queryRunner.query(`ALTER TABLE "organizations" DROP CONSTRAINT "UQ_963693341bd612aa01ddf3a4b68"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updatedAt" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "createdAt" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "resetTokenExpiry"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "resetTokenExpiry" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "lastLogin"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "lastLogin" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "isEmailVerified" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "isActive" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "profilePicture"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "profilePicture" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "organizationId"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "organizationId" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "role"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "role" character varying(50) DEFAULT 'user'`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "lastName"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "lastName" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "firstName"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "firstName" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "password"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "password" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "email" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "users_email_key" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "workflow_templates" DROP COLUMN "isActive"`);
        await queryRunner.query(`ALTER TABLE "workflow_templates" DROP COLUMN "configuration"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "workflow_templates" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "workflow_templates" DROP COLUMN "lastUsedAt"`);
        await queryRunner.query(`ALTER TABLE "workflow_templates" DROP COLUMN "usageCount"`);
        await queryRunner.query(`ALTER TABLE "workflow_templates" DROP COLUMN "tags"`);
        await queryRunner.query(`ALTER TABLE "workflow_templates" DROP COLUMN "version"`);
        await queryRunner.query(`ALTER TABLE "workflow_templates" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."workflow_templates_status_enum"`);
        await queryRunner.query(`ALTER TABLE "workflow_templates" DROP COLUMN "createdBy"`);
        await queryRunner.query(`ALTER TABLE "organizations" DROP COLUMN "size"`);
        await queryRunner.query(`ALTER TABLE "organizations" DROP COLUMN "industry"`);
        await queryRunner.query(`ALTER TABLE "organizations" DROP COLUMN "website"`);
        await queryRunner.query(`ALTER TABLE "organizations" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "organizations" DROP COLUMN "trialEndsAt"`);
        await queryRunner.query(`ALTER TABLE "organizations" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."organizations_status_enum"`);
        await queryRunner.query(`ALTER TABLE "organizations" DROP COLUMN "settings"`);
        await queryRunner.query(`ALTER TABLE "workflow_templates" ADD "deletedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "workflow_templates" ADD "lastUsedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "workflow_templates" ADD "usageCount" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "workflow_templates" ADD "tags" jsonb`);
        await queryRunner.query(`ALTER TABLE "workflow_templates" ADD "version" integer NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE "workflow_templates" ADD "status" "public"."workflow_templates_status_enum" NOT NULL DEFAULT 'draft'`);
        await queryRunner.query(`CREATE INDEX "IDX_WORKFLOW_TEMPLATE_STATUS" ON "workflow_templates" ("status") `);
        await queryRunner.query(`ALTER TABLE "workflow_templates" ADD "createdBy" uuid NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_WORKFLOW_TEMPLATE_CREATED_BY" ON "workflow_templates" ("createdBy") `);
        await queryRunner.query(`ALTER TABLE "projects" ADD "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`DROP TABLE "status_reports"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_AI_ANALYSIS_ORGANIZATION"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_AI_ANALYSIS_USER"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_AI_ANALYSIS_STATUS"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_AI_ANALYSIS_TYPE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_AI_ANALYSIS_CREATED_AT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_AI_ANALYSIS_DOCUMENT_HASH"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_AI_ANALYSIS_COMPOSITE"`);
        await queryRunner.query(`DROP TABLE "ai_analyses"`);
        await queryRunner.query(`DROP TYPE "public"."ai_analyses_confidencelevel_enum"`);
        await queryRunner.query(`DROP TYPE "public"."ai_analyses_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."ai_analyses_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7b356132417fe2de0d091a0c67"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8191cd6f05e030fa59f7c1ed69"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2bf3b4f13cdf45dd0e66d39c88"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0728e1c945a83b0366c9f96c34"`);
        await queryRunner.query(`DROP TABLE "brds"`);
        await queryRunner.query(`DROP TYPE "public"."brds_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f0b43298945e948fa331ce0d9c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0da62e1a1027d022c32eff7390"`);
        await queryRunner.query(`DROP TABLE "brd_analyses"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9516a203d3479f155a56ff27d3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fb450c1b3ed4ccfad85376966f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6e1d50e5619fc3bcddf713822f"`);
        await queryRunner.query(`DROP TABLE "generated_project_plans"`);
        await queryRunner.query(`DROP TYPE "public"."generated_project_plans_methodology_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_EMAIL_VERIFICATION_TOKEN"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_EMAIL_VERIFICATION_USER"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_EMAIL_VERIFICATION_EXPIRES"`);
        await queryRunner.query(`DROP TABLE "email_verifications"`);
        await queryRunner.query(`DROP TYPE "public"."email_verifications_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_FEEDBACK_TYPE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_FEEDBACK_STATUS"`);
        await queryRunner.query(`DROP TABLE "feedback"`);
        await queryRunner.query(`DROP TYPE "public"."feedback_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."feedback_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_INVITATION_TOKEN"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_INVITATION_EMAIL_ORG"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_INVITATION_STATUS"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_INVITATION_EXPIRES"`);
        await queryRunner.query(`DROP TABLE "invitations"`);
        await queryRunner.query(`DROP TYPE "public"."invitations_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."invitations_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d89232e343acb658781b906c62"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7f21464383479f9b76665c08b1"`);
        await queryRunner.query(`DROP TABLE "pm_knowledge_chunks"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e09e2891fd32efaa2ca5234595"`);
        await queryRunner.query(`DROP TABLE "alert_configurations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_intake_submission_created_at"`);
        await queryRunner.query(`DROP TABLE "intake_submissions"`);
        await queryRunner.query(`DROP TYPE "public"."intake_submissions_priority_enum"`);
        await queryRunner.query(`DROP TYPE "public"."intake_submissions_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_intake_form_slug"`);
        await queryRunner.query(`DROP TABLE "intake_forms"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e4e66691a2634fcf5525e33ecf"`);
        await queryRunner.query(`DROP TABLE "portfolios"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_89d3ac584e2551f507bf9730c9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e937b8b9c7c08129635cbcca12"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_44d4dd46e432e62217f8bced6f"`);
        await queryRunner.query(`DROP TABLE "manual_updates"`);
        await queryRunner.query(`DROP TYPE "public"."manual_updates_impact_enum"`);
        await queryRunner.query(`DROP TYPE "public"."manual_updates_category_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_88e460cb86118c8e0f42c93fd1"`);
        await queryRunner.query(`DROP TABLE "performance_baselines"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a99b3ca19aedd64a3f069cdeac"`);
        await queryRunner.query(`DROP TABLE "programs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_846a162364072ebfbecd514622"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_569ac3c1447351deafa2db09f5"`);
        await queryRunner.query(`DROP TABLE "project_metrics"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2221cffeeb64bff14201bd5b3d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2221cffeeb64bff14201bd5b3d"`);
        await queryRunner.query(`DROP TABLE "waitlist"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f47ac4f55eb44910c5fca837bc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_36705f77192f2a56e9e04880f8"`);
        await queryRunner.query(`DROP TABLE "risk_assessments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9966ac1c65e05c4c9f5582d76e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bf6329856d9a15a3504987f109"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ade258af0181b62af135447cd4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_368b6a4812773a963dd41870b5"`);
        await queryRunner.query(`DROP TABLE "risks"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_58908332becb66d6d747a27890"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fc12ad4a736f87e96c0bcde08c"`);
        await queryRunner.query(`DROP TABLE "risk_monitoring"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_63ab5d4c8681a58d0bc079f7ef"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d9a623e83e18b6124bc8383a9c"`);
        await queryRunner.query(`DROP TABLE "risk_responses"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dbcadb4fdd56e827cdeb5b9fb0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_794f6f83be3de83a3e0de0a54e"`);
        await queryRunner.query(`DROP TABLE "stakeholder_communications"`);
        await queryRunner.query(`DROP TABLE "workflow_instances"`);
        await queryRunner.query(`DROP TYPE "public"."workflow_instances_priority_enum"`);
        await queryRunner.query(`DROP TYPE "public"."workflow_instances_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b8b247beebde4bcd470d1b0272"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ee0c5b6e142c99abdebfaf4b07"`);
        await queryRunner.query(`DROP TABLE "resource_allocations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fdba7c2e9f191ed27416475913"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ef7da82084d0de2927d7f95579"`);
        await queryRunner.query(`DROP TABLE "project_tasks"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ea733ff193912a2ec4dc294dc6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fc694bf852ad3894693c3046e5"`);
        await queryRunner.query(`DROP TABLE "user_projects"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fee3e62124842d117f5f425d3a"`);
        await queryRunner.query(`DROP TABLE "project_stakeholders"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_70b83a30fc8a2d5a59e3a702ed"`);
        await queryRunner.query(`DROP TABLE "project_risks"`);
        await queryRunner.query(`DROP TABLE "teams"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_TEAM_MEMBER_UNIQUE"`);
        await queryRunner.query(`DROP TABLE "team_members"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ROLE_NAME"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TYPE "public"."roles_name_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a0bddfb3573a2b4c68cae63be1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6ffdb745d89e02fbe2134a33a5"`);
        await queryRunner.query(`DROP TABLE "resource_conflicts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_WORKFLOW_STAGE_TEMPLATE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_WORKFLOW_STAGE_ORDER"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_WORKFLOW_STAGE_TYPE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_WORKFLOW_STAGE_STATUS"`);
        await queryRunner.query(`DROP TABLE "workflow_stages"`);
        await queryRunner.query(`DROP TYPE "public"."workflow_stages_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."workflow_stages_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_WORKFLOW_APPROVAL_STAGE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_WORKFLOW_APPROVAL_REVIEWER"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_WORKFLOW_APPROVAL_STATUS"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_WORKFLOW_APPROVAL_TYPE"`);
        await queryRunner.query(`DROP TABLE "workflow_approvals"`);
        await queryRunner.query(`DROP TYPE "public"."workflow_approvals_level_enum"`);
        await queryRunner.query(`DROP TYPE "public"."workflow_approvals_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."workflow_approvals_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_WORKFLOW_TEMPLATE_ORG"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_WORKFLOW_TEMPLATE_TYPE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_WORKFLOW_TEMPLATE_STATUS"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_WORKFLOW_TEMPLATE_CREATED_BY"`);
        await queryRunner.query(`DROP TABLE "workflow_templates"`);
        await queryRunner.query(`DROP TYPE "public"."workflow_templates_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."workflow_templates_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_WORKFLOW_VERSION_TEMPLATE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_WORKFLOW_VERSION_NUMBER"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_WORKFLOW_VERSION_CREATED_BY"`);
        await queryRunner.query(`DROP TABLE "workflow_versions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_USER_ORG_USER_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_USER_ORG_ORG_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_USER_ORG_ACTIVE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_USER_ORG_ROLE"`);
        await queryRunner.query(`DROP TABLE "user_organizations"`);
        await queryRunner.query(`DROP TYPE "public"."user_organizations_role_enum"`);
        await queryRunner.query(`DROP TABLE "refresh_tokens"`);
        await queryRunner.query(`CREATE INDEX "IDX_users_email_verified" ON "users" ("emailVerified") `);
        await queryRunner.query(`CREATE INDEX "IDX_users_verification_token" ON "users" ("verificationToken") `);
        await queryRunner.query(`CREATE INDEX "IDX_users_reset_token" ON "users" ("resetToken") `);
    }

}
