# Zephix Frontend - Enterprise Railway Configuration
# Explicitly configured to use Dockerfile and prevent npm script auto-detection

[build]
builder = "nixpacks"
buildCommand = "npm ci && npm run build"

[deploy]
startCommand = "npm run preview"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environments.production]
buildCommand = "npm ci && npm run build"
startCommand = "npm run preview"

# Environment variables
[variables]
NODE_ENV = "production"
PORT = "80"
VITE_API_BASE_URL = "https://getzephix.com/api"
VITE_APP_NAME = "Zephix AI"
VITE_APP_VERSION = "2.0.0"

# Resource allocation
[resources]
cpu = "0.25"
memory = "256MB"

# Explicitly declare this is NOT a Node.js service
[metadata]
type = "static"
framework = "nginx"
language = "none"
