[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[variables]
NODE_ENV = "production"
VITE_API_BASE_URL = "https://getzephix.com/api"
VITE_APP_NAME = "Zephix AI"
VITE_APP_VERSION = "2.0.0"
