[build]
builder = "nixpacks"
buildCommand = "npm ci && npm run build"

[deploy]
startCommand = "npm run preview -- --host 0.0.0.0 --port ${PORT:-3000}"
restartPolicyType = "always"

[env]
NODE_ENV = "production"
