# Zephix Frontend - Enterprise Railway Configuration
# Explicitly configured to use Dockerfile and prevent npm script auto-detection

[build]
builder = "DOCKERFILE"

[deploy]
# Explicitly disable npm script detection
startCommand = ""
# Force use of Dockerfile CMD/ENTRYPOINT
useDockerfile = true
# Health check configuration
healthcheckPath = "/health"
healthcheckTimeout = 300
# Restart policy
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Environment variables
[variables]
NODE_ENV = "production"
PORT = "80"
VITE_API_BASE_URL = "https://getzephix.com/api"
VITE_APP_NAME = "Zephix AI"
VITE_APP_VERSION = "2.0.0"

# Resource allocation
[resources]
cpu = "0.25"
memory = "256MB"

# Explicitly declare this is NOT a Node.js service
[metadata]
type = "static"
framework = "nginx"
language = "none"
