[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile.railway"

[deploy]
startCommand = ""
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
