name: build-frontend
on:
  push:
    branches: [ "main" ]
    paths:
      - "zephix-frontend/**"
      - ".github/workflows/frontend.yml"
permissions:
  contents: read
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/zephix-frontend
          tags: |
            type=sha,prefix=sha-
            type=raw,value=main,enable={{is_default_branch}}
      - uses: docker/build-push-action@v6
        with:
          context: ./zephix-frontend
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VITE_API_URL=https://api.getzephix.com
